In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("/content/UrbanKart_Customer_Analytics_Master.csv")
df

FileNotFoundError: [Errno 2] No such file or directory: '/content/UrbanKart_Customer_Analytics_Master.csv'

In [ ]:
df.head(10)

,Customer_ID,Customer_Name,Age,Gender,City_Tier,Income,Customer_Tenure_Months,Acquisition_Channel,Website_Visits_Monthly,App_Sessions_Monthly,...,Payment_Delay_Count,Loyalty_Points,Marketing_Response_Rate,Annual_Revenue,Churn,Purchase_Next_30_Days,Customer_Lifetime_Value,Preferred_Category,Preferred_Channel,Customer_Value_Segment
0,CUST000001,Aryan Maharaj,23,Female,Tier 3,471173.0,54,Offline Store,8.0,12.0,...,0,119,0.017,29211.42,0,1,33024.39,Electronics,Website,Medium Value
1,CUST000002,Udant Dewan,37,Female,Tier 2,150000.0,28,Organic Search,20.0,16.0,...,0,1191,0.330,163225.27,0,0,137497.85,Electronics,Website,High Value
2,CUST000003,Gagan Sami,36,Female,Tier 2,1089061.0,18,Affiliate,9.0,12.0,...,0,973,0.229,92828.35,0,1,64319.68,Electronics,Physical Store,High Value
3,CUST000004,Ayushman Chander,40,Male,Tier 1,661655.0,11,Social Media,9.0,5.0,...,2,52,0.132,8063.92,1,0,2384.79,Grocery,Website,Low Value
4,CUST000005,Viraj Tiwari,58,Male,Tier 1,220959.0,10,Social Media,11.0,9.0,...,0,55,0.258,9955.62,0,0,4263.70,Fashion,Mobile App,Low Value
5,CUST000006,Rushil Saini,35,Female,Tier 1,434781.0,45,Paid Search,10.0,10.0,...,0,747,0.258,136119.06,0,0,145518.09,Books,Website,High Value
6,CUST000007,Saumya Mall,26,Male,Tier 2,539489.0,58,Paid Search,4.0,6.0,...,0,13,0.000,500.00,1,1,411.13,Accessories,Website,Low Value
7,CUST000008,Nathaniel Sami,43,Male,Tier 2,296729.0,27,Referral,12.0,12.0,...,1,30,0.369,48727.42,0,0,34166.01,Fashion,Physical Store,Medium Value
8,CUST000009,Arunima Dugal,59,Male,Tier 3,344461.0,19,Offline Store,9.0,9.0,...,2,139,0.041,99740.73,1,0,12182.45,Fashion,Website,Low Value
9,CUST000010,Gayathri Chaudry,49,Male,Tier 3,518312.0,22,Paid Search,12.0,10.0,...,0,22,0.174,500.00,0,0,234.20,Accessories,Mobile App,Low Value

In [ ]:
df.tail(10)

,Customer_ID,Customer_Name,Age,Gender,City_Tier,Income,Customer_Tenure_Months,Acquisition_Channel,Website_Visits_Monthly,App_Sessions_Monthly,...,Payment_Delay_Count,Loyalty_Points,Marketing_Response_Rate,Annual_Revenue,Churn,Purchase_Next_30_Days,Customer_Lifetime_Value,Preferred_Category,Preferred_Channel,Customer_Value_Segment
19990,CUST019991,Alexander Nath,50,Male,Tier 1,660966.0,51,Social Media,17.0,23.0,...,1,131,0.357,53378.57,1,1,44738.87,Grocery,Marketplace,Medium Value
19991,CUST019992,Niharika Madan,30,Female,Tier 1,320473.0,26,Marketplace,13.0,15.0,...,0,28,0.448,508.80,0,0,366.97,Accessories,Physical Store,Low Value
19992,CUST019993,Libni Singh,42,Female,Tier 1,1574068.0,69,Organic Search,1.0,10.0,...,0,36,0.000,53162.36,0,1,56551.17,Home & Kitchen,Marketplace,High Value
19993,CUST019994,Kashvi Khosla,49,Male,Tier 2,1509536.0,14,Offline Store,7.0,8.0,...,1,280,0.273,112962.36,0,0,51078.96,Beauty & Personal Care,Marketplace,Medium Value
19994,CUST019995,Jack Talwar,18,Female,Tier 3,263104.0,39,Organic Search,5.0,13.0,...,0,61,0.000,5222.23,0,1,6508.54,Sports & Fitness,Mobile App,Low Value
19995,CUST019996,Advik Sachdev,46,Female,Tier 1,499169.0,33,Offline Store,15.0,9.0,...,1,425,0.332,62862.55,0,1,64436.02,Home & Kitchen,Mobile App,High Value
19996,CUST019997,Yug Upadhyay,42,Female,Tier 1,945257.0,15,Organic Search,4.0,2.0,...,2,11,0.133,509.19,1,0,170.81,Grocery,Website,Low Value
19997,CUST019998,Priya Golla,24,Male,Tier 1,1680032.0,61,Email,7.0,15.0,...,2,131,0.223,36693.97,0,0,34248.61,Sports & Fitness,Mobile App,Medium Value
19998,CUST019999,Charita Ray,32,Male,Tier 2,312155.0,44,Referral,10.0,18.0,...,0,1460,0.024,76552.31,1,0,89562.24,Electronics,Physical Store,High Value
19999,CUST020000,Wazir Borah,25,Male,Tier 1,572246.0,17,Marketplace,4.0,3.0,...,0,61,0.000,497.18,1,0,176.98,Fashion,Physical Store,Low Value

In [ ]:
df.columns

Index(['Customer_ID', 'Customer_Name', 'Age', 'Gender', 'City_Tier', 'Income',
       'Customer_Tenure_Months', 'Acquisition_Channel',
       'Website_Visits_Monthly', 'App_Sessions_Monthly',
       'Purchase_Frequency_Monthly', 'Average_Order_Value',
       'Discount_Usage_Rate', 'Orders_Last_12M', 'Days_Since_Last_Purchase',
       'Return_Rate', 'Support_Tickets_12M', 'Customer_Satisfaction_Score',
       'Payment_Delay_Count', 'Loyalty_Points', 'Marketing_Response_Rate',
       'Annual_Revenue', 'Churn', 'Purchase_Next_30_Days',
       'Customer_Lifetime_Value', 'Preferred_Category', 'Preferred_Channel',
       'Customer_Value_Segment'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 28 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Customer_ID                  20000 non-null  object
 1   Customer_Name                20000 non-null  object
 2   Age                          20000 non-null  int64
 3   Gender                       20000 non-null  object
 4   City_Tier                    20000 non-null  object
 5   Income                       19400 non-null  float64
 6   Customer_Tenure_Months       20000 non-null  int64
 7   Acquisition_Channel          19600 non-null  object
 8   Website_Visits_Monthly       19300 non-null  float64
 9   App_Sessions_Monthly         19400 non-null  float64
 10  Purchase_Frequency_Monthly   20000 non-null  float64
 11  Average_Order_Value          20000 non-null  float64
 12  Discount_Usage_Rate          20000 non-null  float64
 13  Orders_Last_12M              20000 non-null  int64
 14  Days_Since_Last_Purchase     20000 non-null  int64
 15  Return_Rate                  20000 non-null  float64
 16  Support_Tickets_12M          20000 non-null  int64
 17  Customer_Satisfaction_Score  19200 non-null  float64
 18  Payment_Delay_Count          20000 non-null  int64
 19  Loyalty_Points               20000 non-null  int64
 20  Marketing_Response_Rate      19400 non-null  float64
 21  Annual_Revenue               20000 non-null  float64
 22  Churn                        20000 non-null  int64
 23  Purchase_Next_30_Days        20000 non-null  int64
 24  Customer_Lifetime_Value      20000 non-null  float64
 25  Preferred_Category           19500 non-null  object
 26  Preferred_Channel            20000 non-null  object
 27  Customer_Value_Segment       20000 non-null  object
dtypes: float64(11), int64(9), object(8)
memory usage: 4.3+ MB

In [ ]:
df.describe()

,Age,Income,Customer_Tenure_Months,Website_Visits_Monthly,App_Sessions_Monthly,Purchase_Frequency_Monthly,Average_Order_Value,Discount_Usage_Rate,Orders_Last_12M,Days_Since_Last_Purchase,Return_Rate,Support_Tickets_12M,Customer_Satisfaction_Score,Payment_Delay_Count,Loyalty_Points,Marketing_Response_Rate,Annual_Revenue,Churn,Purchase_Next_30_Days,Customer_Lifetime_Value
count,20000.000000,1.940000e+04,20000.000000,19300.000000,19400.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,19200.000000,20000.000000,20000.000000,19400.00000,20000.000000,20000.000000,20000.000000,20000.000000
mean,38.193900,5.921987e+05,24.061250,12.323990,13.882990,0.537693,1845.453168,0.406639,6.611900,72.452850,0.132860,0.969450,3.505293,0.813400,230.278750,0.25482,44288.260337,0.247000,0.451750,32197.683549
std,11.477238,4.353917e+05,15.600688,9.169258,10.394052,0.386064,1350.782124,0.200085,5.540155,69.246223,0.097917,1.554296,0.823314,0.975155,397.115611,0.21910,46386.761759,0.431278,0.497679,38963.674642
min,18.000000,1.500000e+05,1.000000,0.000000,0.000000,0.100000,170.560000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.00000,491.190000,0.000000,0.000000,64.760000
25%,30.000000,2.991995e+05,12.000000,6.000000,7.000000,0.280000,962.485000,0.254000,3.000000,26.000000,0.059000,0.000000,3.000000,0.000000,43.000000,0.05500,4851.805000,0.000000,0.000000,2543.910000
50%,38.000000,4.707170e+05,21.000000,10.000000,11.000000,0.440000,1464.940000,0.394000,5.000000,50.000000,0.118000,0.000000,3.610000,1.000000,106.000000,0.22400,32966.325000,0.000000,0.000000,20346.305000
75%,46.000000,7.437775e+05,32.000000,16.000000,18.000000,0.680000,2291.930000,0.550000,9.000000,94.000000,0.190000,2.000000,4.110000,1.000000,254.000000,0.40000,67364.075000,0.000000,1.000000,46801.957500
max,70.000000,5.000000e+06,72.000000,167.000000,135.000000,5.050000,27993.310000,1.000000,75.000000,365.000000,0.663000,21.000000,5.000000,8.000000,9649.000000,1.00000,513835.370000,1.000000,1.000000,466257.010000

In [ ]:
df.isnull().sum()

Customer_ID                      0
Customer_Name                    0
Age                              0
Gender                           0
City_Tier                        0
Income                         600
Customer_Tenure_Months           0
Acquisition_Channel            400
Website_Visits_Monthly         700
App_Sessions_Monthly           600
Purchase_Frequency_Monthly       0
Average_Order_Value              0
Discount_Usage_Rate              0
Orders_Last_12M                  0
Days_Since_Last_Purchase         0
Return_Rate                      0
Support_Tickets_12M              0
Customer_Satisfaction_Score    800
Payment_Delay_Count              0
Loyalty_Points                   0
Marketing_Response_Rate        600
Annual_Revenue                   0
Churn                            0
Purchase_Next_30_Days            0
Customer_Lifetime_Value          0
Preferred_Category             500
Preferred_Channel                0
Customer_Value_Segment           0
dtype: int64

In [ ]:
df['Acquisition_Channel'].head() #replace by mode

0     Offline Store
1    Organic Search
2         Affiliate
3      Social Media
4      Social Media
Name: Acquisition_Channel, dtype: object

In [ ]:
df['Website_Visits_Monthly'].head() #replace by mode

0     8.0
1    20.0
2     9.0
3     9.0
4    11.0
Name: Website_Visits_Monthly, dtype: float64

In [ ]:
df['Customer_Satisfaction_Score'].head() #replace by median

0    4.29
1    3.46
2    4.14
3    1.43
4    3.91
Name: Customer_Satisfaction_Score, dtype: float64

In [ ]:
df['Marketing_Response_Rate'].head() #replace by median

0    0.017
1    0.330
2    0.229
3    0.132
4    0.258
Name: Marketing_Response_Rate, dtype: float64

In [ ]:
df['Income'].head() #replace by median

0     471173.0
1     150000.0
2    1089061.0
3     661655.0
4     220959.0
Name: Income, dtype: float64

In [ ]:
for i in ['Customer_Satisfaction_Score','Marketing_Response_Rate','Income']:
  df[i]=df[i].fillna(df[i].median())

In [ ]:
df['Customer_Satisfaction_Score'].isnull().sum()

np.int64(0)

In [ ]:
for j in ['Website_Visits_Monthly','Preferred_Category','App_Sessions_Monthly','Acquisition_Channel']:
  df[j] = df[j].fillna(df[j].mode()[0])

In [ ]:
df['Income'].isnull().sum()

np.int64(0)

In [ ]:
X = df[['Income']]
y= df['Annual_Revenue']

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=11)

In [ ]:
print(X_train.shape,X_test.shape,y_train.shape,y_test.shape)

(15000, 1) (5000, 1) (15000,) (5000,)

In [ ]:
X_test.head()

         Income
2440   433335.0
7382   512454.0
13064  432392.0
18810  593137.0
359    298622.0

In [ ]:
from sklearn.linear_model import LinearRegression
model_1 = LinearRegression()

In [ ]:
model_1.fit(X_train,y_train)

LinearRegression()

In [ ]:
y_pred = model_1.predict(X_test)

In [ ]:
print(y_test,y_pred)

2440      39316.23
7382      80480.01
13064     46388.43
18810       500.00
359       66256.62
           ...
7916      82811.71
14288     28906.37
7209      61515.83
6534      70520.72
1683     103976.81
Name: Annual_Revenue, Length: 5000, dtype: float64 [39191.15383353 41647.11749015 39161.8818037  ... 56780.22920913
 33999.9781848  53916.75419766]

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.7701484942387564

In [ ]:
X = df[["Income",'Website_Visits_Monthly',"Customer_Tenure_Months","Purchase_Frequency_Monthly","Average_Order_Value"]]
y = df['Annual_Revenue']

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=11)
model_1 = LinearRegression()
model_1.fit(X_train,y_train)
y_pred = model_1.predict(X_test)
print(r2_score(y_test,y_pred))

0.7701484942387564